# Generated by Django 5.2.7 on 2026-01-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
